import { query } from '@/app/lib/db';

interface CreateUserInput {
  email: string;
  firstName: string;
  middleName?: string | null;
  lastName: string;
  residentCountry: string;
  homeCurrency: string;
}

interface User {
  user_id: string;
  email: string;
  first_name: string;
  middle_name: string | null;
  last_name: string;
  resident_country: string;
  home_currency: string;
  is_active: number;
  created_at: string;
}

export async function createUser(input: CreateUserInput): Promise<User> {
  try {
    // Check if email already exists
    const existingUsers = await query<{ email: string }>(
      'SELECT email FROM users WHERE email = ?',
      [input.email]
    );

    if (existingUsers.length > 0) {
      throw new Error('Email already registered');
    }

    // Insert new user (user_id will be auto-generated by trigger)
    await query(
      `INSERT INTO users (
        user_id, email, first_name, middle_name, last_name, 
        resident_country, home_currency
      ) VALUES (NULL, ?, ?, ?, ?, ?, ?)`,
      [
        input.email,
        input.firstName,
        input.middleName || null,
        input.lastName,
        input.residentCountry,
        input.homeCurrency,
      ]
    );

    // Fetch the created user
    const users = await query<User>(
      'SELECT * FROM users WHERE email = ?',
      [input.email]
    );

    if (users.length === 0) {
      throw new Error('User creation failed');
    }

    return users[0];
  } catch (error) {
    console.error('Error creating user:', error);
    throw error;
  }
}

export async function getUserByEmail(email: string): Promise<User | null> {
  try {
    const users = await query<User>(
      'SELECT * FROM users WHERE email = ? AND is_active = 1',
      [email]
    );
    return users.length > 0 ? users[0] : null;
  } catch (error) {
    console.error('Error fetching user:', error);
    throw error;
  }
}

export async function getUserById(userId: string): Promise<User | null> {
  try {
    const users = await query<User>(
      'SELECT * FROM users WHERE user_id = ? AND is_active = 1',
      [userId]
    );
    return users.length > 0 ? users[0] : null;
  } catch (error) {
    console.error('Error fetching user:', error);
    throw error;
  }
}